// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/SparseChol.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sparse_chol_crs
Rcpp::List sparse_chol_crs(int n, std::vector<int> Ap, std::vector<int> Ai, std::vector<double> Ax);
RcppExport SEXP _SparseChol_sparse_chol_crs(SEXP nSEXP, SEXP ApSEXP, SEXP AiSEXP, SEXP AxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type Ap(ApSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type Ai(AiSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type Ax(AxSEXP);
    rcpp_result_gen = Rcpp::wrap(sparse_chol_crs(n, Ap, Ai, Ax));
    return rcpp_result_gen;
END_RCPP
}
// sparse_chol
SEXP sparse_chol(Rcpp::NumericMatrix mat);
RcppExport SEXP _SparseChol_sparse_chol(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(sparse_chol(mat));
    return rcpp_result_gen;
END_RCPP
}
// amd_order
SEXP amd_order(Rcpp::NumericMatrix mat);
RcppExport SEXP _SparseChol_amd_order(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(amd_order(mat));
    return rcpp_result_gen;
END_RCPP
}
// dense_to_sparse
Rcpp::List dense_to_sparse(Rcpp::NumericMatrix mat);
RcppExport SEXP _SparseChol_dense_to_sparse(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(dense_to_sparse(mat));
    return rcpp_result_gen;
END_RCPP
}
// testSparse
void testSparse();
RcppExport SEXP _SparseChol_testSparse() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    testSparse();
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SparseChol_sparse_chol_crs", (DL_FUNC) &_SparseChol_sparse_chol_crs, 4},
    {"_SparseChol_sparse_chol", (DL_FUNC) &_SparseChol_sparse_chol, 1},
    {"_SparseChol_amd_order", (DL_FUNC) &_SparseChol_amd_order, 1},
    {"_SparseChol_dense_to_sparse", (DL_FUNC) &_SparseChol_dense_to_sparse, 1},
    {"_SparseChol_testSparse", (DL_FUNC) &_SparseChol_testSparse, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_SparseChol(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
