# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sparse Cholesky decomposition
#' 
#' Sparse Cholesky decomposition
#' 
#' @details
#' Generates the LDL decomposition of a symmetrix, sparse matrix using the method 
#' described by Timothy Davis (see references). Required input is a matrix
#' in sparse format from the matrix package, see \link[Matrix]{sparseMatrix}
#' @param n Integer specifying the dimension of the matrix
#' @param Ai Integer vector specifying the row positions of the non-zero values of the matrix
#' @param Ap numeric (integer valued) vector of pointers, one for each column (or row), to the initial (zero-based) index of elements in the column (or row).
#' @param Ax values of the non-zero matrix entries
#' @return A list with elements n, Ai, Ap, Ax (corresponding to above arguments) for matrix L, and element D, which 
#' contains the diagonal values of matrix D.
sparse_chol <- function(n, Ap, Ai, Ax) {
    .Call(`_SparseChol_sparse_chol`, n, Ap, Ai, Ax)
}

